### ISSUE TITLE
[화면] Admin Page

### ISSUE THREAD

**Issue by ottl-seo** [ottl-seo/GDSC-Recruiting-FE#18]
### 1. 관리자 메인 페이지
- 지원 수 현황
- 코어/일반 멤버 조회 페이지로 이동

### 2. 코어 멤버 지원서 페이지
- 지원자 리스트 확인 (번호, 이름)
- 코어 멤버 지원서 확인
- 합/불합 체크 기능

### 3. 일반 멤버 지원서 확인 페이지
- 지원자 리스트 확인 (번호, 이름)
- 멤버 지원서 확인
- 합/불합 체크 기능

- - - 
#### +시간이 된다면...
자동으로 서류 결과 메일 보내주는 기능까지

**Comment by ottlseo** [comment]
보안상 새로운 레포에 코드 저장해야 할듯
security 적용하기에는 너무 시간이 오래걸릴것 같아서 나만 아는 비밀 URL로 접근하게 하려고 함. 
- [x] 배포도 따로 진행
